/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type {
  AuthResponse,
  LoginRequest,
  RegisterRequest,
} from "../../schemas";

import { customAxios } from "../../axiosInstance";

export const getAuth = () => {
  /**
   * @summary Login
   */
  const loginApiAuthLoginPost = (loginRequest: LoginRequest) => {
    return customAxios<AuthResponse>({
      url: `/api/v1/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginRequest,
    });
  };
  /**
   * @summary Register
   */
  const registerApiAuthRegisterPost = (registerRequest: RegisterRequest) => {
    return customAxios<AuthResponse>({
      url: `/api/v1/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerRequest,
    });
  };
  return { loginApiAuthLoginPost, registerApiAuthRegisterPost };
};
export type LoginApiAuthLoginPostResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["loginApiAuthLoginPost"]>>
>;
export type RegisterApiAuthRegisterPostResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["registerApiAuthRegisterPost"]>>
>;
