from pydantic import BaseModel, EmailStr
from typing import Optional
from datetime import datetime

class ActeCreate(BaseModel):
    type_acte: Optional[str]
    numero: str
    timbre: Optional[str]
    date_creation: Optional[datetime]
    classification: Optional[str]
    objet: Optional[str]
    statut: Optional[str]
    description: Optional[str]
    mots_cles: Optional[str]
    date_entree_vigueur: Optional[datetime]
    date_expiration: Optional[datetime]
    date_enregistrement: Optional[datetime]
    auteur: Optional[str]
    signataires: Optional[str]
    fichier_associe: Optional[str]
    base_legale: Optional[str]
    public_cible: Optional[str]
    domaine_application: Optional[str]
    lieu_application: Optional[str]
    acte_modifie_par: Optional[str]
    version: Optional[int]
    utilisateur_modification: Optional[str]
    actes_references: Optional[str]
    actes_applications: Optional[str]
    actes_modifies: Optional[str]
    actes_modificateurs: Optional[str]
    actes_enfants: Optional[str]
    acte_original: Optional[str]

class ActeRead(ActeCreate):
    id: int

class ActeUpdate(BaseModel):
    numero: Optional[str]
    objet: Optional[str]
    type_acte: Optional[str]
    description: Optional[str]
    date_creation: Optional[datetime]
    date_entree_vigueur: Optional[datetime]
    date_expiration: Optional[datetime]
    auteur: Optional[str]
    base_legale: Optional[str]
    public_cible: Optional[str]
    domaine_application: Optional[str]
    lieu_application: Optional[str]
    timbre: Optional[str]
    classification: Optional[str]
    mots_cles: Optional[str]
    statut: Optional[str]
    acte_modifie_par: Optional[str]
    signataires: Optional[str]
    version: Optional[int]
    fichier_associe: Optional[str]
    date_enregistrement: Optional[datetime]
    utilisateur_modification: Optional[str]
    actes_references: Optional[str]
    actes_applications: Optional[str]
    actes_modifies: Optional[str]
    actes_modificateurs: Optional[str]
    actes_enfants: Optional[str]
    acte_original: Optional[str]
