/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { ActeCreateObjet } from './acteCreateObjet';
import type { ActeCreateTypeActe } from './acteCreateTypeActe';
import type { ActeCreateDescription } from './acteCreateDescription';
import type { ActeCreateDateCreation } from './acteCreateDateCreation';
import type { ActeCreateDateEntreeVigueur } from './acteCreateDateEntreeVigueur';
import type { ActeCreateDateExpiration } from './acteCreateDateExpiration';
import type { ActeCreateAuteur } from './acteCreateAuteur';
import type { ActeCreateBaseLegale } from './acteCreateBaseLegale';
import type { ActeCreatePublicCible } from './acteCreatePublicCible';
import type { ActeCreateDomaineApplication } from './acteCreateDomaineApplication';
import type { ActeCreateLieuApplication } from './acteCreateLieuApplication';
import type { ActeCreateTimbre } from './acteCreateTimbre';
import type { ActeCreateClassification } from './acteCreateClassification';
import type { ActeCreateMotsCles } from './acteCreateMotsCles';
import type { ActeCreateStatut } from './acteCreateStatut';
import type { ActeCreateActeModifiePar } from './acteCreateActeModifiePar';
import type { ActeCreateSignataires } from './acteCreateSignataires';
import type { ActeCreateVersion } from './acteCreateVersion';
import type { ActeCreateFichierAssocie } from './acteCreateFichierAssocie';
import type { ActeCreateDateEnregistrement } from './acteCreateDateEnregistrement';
import type { ActeCreateUtilisateurModification } from './acteCreateUtilisateurModification';
import type { ActeCreateActesReferences } from './acteCreateActesReferences';
import type { ActeCreateActesApplications } from './acteCreateActesApplications';
import type { ActeCreateActesModifies } from './acteCreateActesModifies';
import type { ActeCreateActesModificateurs } from './acteCreateActesModificateurs';
import type { ActeCreateActesEnfants } from './acteCreateActesEnfants';
import type { ActeCreateActeOriginal } from './acteCreateActeOriginal';

export interface ActeCreate {
  numero: string;
  objet: ActeCreateObjet;
  type_acte: ActeCreateTypeActe;
  description: ActeCreateDescription;
  date_creation: ActeCreateDateCreation;
  date_entree_vigueur: ActeCreateDateEntreeVigueur;
  date_expiration: ActeCreateDateExpiration;
  auteur: ActeCreateAuteur;
  base_legale: ActeCreateBaseLegale;
  public_cible: ActeCreatePublicCible;
  domaine_application: ActeCreateDomaineApplication;
  lieu_application: ActeCreateLieuApplication;
  timbre: ActeCreateTimbre;
  classification: ActeCreateClassification;
  mots_cles: ActeCreateMotsCles;
  statut: ActeCreateStatut;
  acte_modifie_par: ActeCreateActeModifiePar;
  signataires: ActeCreateSignataires;
  version: ActeCreateVersion;
  fichier_associe: ActeCreateFichierAssocie;
  date_enregistrement: ActeCreateDateEnregistrement;
  utilisateur_modification: ActeCreateUtilisateurModification;
  actes_references: ActeCreateActesReferences;
  actes_applications: ActeCreateActesApplications;
  actes_modifies: ActeCreateActesModifies;
  actes_modificateurs: ActeCreateActesModificateurs;
  actes_enfants: ActeCreateActesEnfants;
  acte_original: ActeCreateActeOriginal;
}
