/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { ActeReadTypeActe } from "./acteReadTypeActe";
import type { ActeReadTimbre } from "./acteReadTimbre";
import type { ActeReadDateCreation } from "./acteReadDateCreation";
import type { ActeReadClassification } from "./acteReadClassification";
import type { ActeReadObjet } from "./acteReadObjet";
import type { ActeReadStatut } from "./acteReadStatut";
import type { ActeReadDescription } from "./acteReadDescription";
import type { ActeReadMotsCles } from "./acteReadMotsCles";
import type { ActeReadDateEntreeVigueur } from "./acteReadDateEntreeVigueur";
import type { ActeReadDateExpiration } from "./acteReadDateExpiration";
import type { ActeReadDateEnregistrement } from "./acteReadDateEnregistrement";
import type { ActeReadAuteur } from "./acteReadAuteur";
import type { ActeReadSignataires } from "./acteReadSignataires";
import type { ActeReadFichierAssocie } from "./acteReadFichierAssocie";
import type { ActeReadBaseLegale } from "./acteReadBaseLegale";
import type { ActeReadPublicCible } from "./acteReadPublicCible";
import type { ActeReadDomaineApplication } from "./acteReadDomaineApplication";
import type { ActeReadLieuApplication } from "./acteReadLieuApplication";
import type { ActeReadActeModifiePar } from "./acteReadActeModifiePar";
import type { ActeReadVersion } from "./acteReadVersion";
import type { ActeReadUtilisateurModification } from "./acteReadUtilisateurModification";
import type { ActeReadActesReferences } from "./acteReadActesReferences";
import type { ActeReadActesApplications } from "./acteReadActesApplications";
import type { ActeReadActesModifies } from "./acteReadActesModifies";
import type { ActeReadActesModificateurs } from "./acteReadActesModificateurs";
import type { ActeReadActesEnfants } from "./acteReadActesEnfants";
import type { ActeReadActeOriginal } from "./acteReadActeOriginal";

export interface ActeRead {
  type_acte: ActeReadTypeActe;
  numero: string;
  timbre: ActeReadTimbre;
  date_creation: ActeReadDateCreation;
  classification: ActeReadClassification;
  objet: ActeReadObjet;
  statut: ActeReadStatut;
  description: ActeReadDescription;
  mots_cles: ActeReadMotsCles;
  date_entree_vigueur: ActeReadDateEntreeVigueur;
  date_expiration: ActeReadDateExpiration;
  date_enregistrement: ActeReadDateEnregistrement;
  auteur: ActeReadAuteur;
  signataires: ActeReadSignataires;
  fichier_associe: ActeReadFichierAssocie;
  base_legale: ActeReadBaseLegale;
  public_cible: ActeReadPublicCible;
  domaine_application: ActeReadDomaineApplication;
  lieu_application: ActeReadLieuApplication;
  acte_modifie_par: ActeReadActeModifiePar;
  version: ActeReadVersion;
  utilisateur_modification: ActeReadUtilisateurModification;
  actes_references: ActeReadActesReferences;
  actes_applications: ActeReadActesApplications;
  actes_modifies: ActeReadActesModifies;
  actes_modificateurs: ActeReadActesModificateurs;
  actes_enfants: ActeReadActesEnfants;
  acte_original: ActeReadActeOriginal;
  id: number;
}
