/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { ActeUpdateNumero } from "./acteUpdateNumero";
import type { ActeUpdateObjet } from "./acteUpdateObjet";
import type { ActeUpdateTypeActe } from "./acteUpdateTypeActe";
import type { ActeUpdateDescription } from "./acteUpdateDescription";
import type { ActeUpdateDateCreation } from "./acteUpdateDateCreation";
import type { ActeUpdateDateEntreeVigueur } from "./acteUpdateDateEntreeVigueur";
import type { ActeUpdateDateExpiration } from "./acteUpdateDateExpiration";
import type { ActeUpdateAuteur } from "./acteUpdateAuteur";
import type { ActeUpdateBaseLegale } from "./acteUpdateBaseLegale";
import type { ActeUpdatePublicCible } from "./acteUpdatePublicCible";
import type { ActeUpdateDomaineApplication } from "./acteUpdateDomaineApplication";
import type { ActeUpdateLieuApplication } from "./acteUpdateLieuApplication";
import type { ActeUpdateTimbre } from "./acteUpdateTimbre";
import type { ActeUpdateClassification } from "./acteUpdateClassification";
import type { ActeUpdateMotsCles } from "./acteUpdateMotsCles";
import type { ActeUpdateStatut } from "./acteUpdateStatut";
import type { ActeUpdateActeModifiePar } from "./acteUpdateActeModifiePar";
import type { ActeUpdateSignataires } from "./acteUpdateSignataires";
import type { ActeUpdateVersion } from "./acteUpdateVersion";
import type { ActeUpdateFichierAssocie } from "./acteUpdateFichierAssocie";
import type { ActeUpdateDateEnregistrement } from "./acteUpdateDateEnregistrement";
import type { ActeUpdateUtilisateurModification } from "./acteUpdateUtilisateurModification";
import type { ActeUpdateActesReferences } from "./acteUpdateActesReferences";
import type { ActeUpdateActesApplications } from "./acteUpdateActesApplications";
import type { ActeUpdateActesModifies } from "./acteUpdateActesModifies";
import type { ActeUpdateActesModificateurs } from "./acteUpdateActesModificateurs";
import type { ActeUpdateActesEnfants } from "./acteUpdateActesEnfants";
import type { ActeUpdateActeOriginal } from "./acteUpdateActeOriginal";

export interface ActeUpdate {
  numero: ActeUpdateNumero;
  objet: ActeUpdateObjet;
  type_acte: ActeUpdateTypeActe;
  description: ActeUpdateDescription;
  date_creation: ActeUpdateDateCreation;
  date_entree_vigueur: ActeUpdateDateEntreeVigueur;
  date_expiration: ActeUpdateDateExpiration;
  auteur: ActeUpdateAuteur;
  base_legale: ActeUpdateBaseLegale;
  public_cible: ActeUpdatePublicCible;
  domaine_application: ActeUpdateDomaineApplication;
  lieu_application: ActeUpdateLieuApplication;
  timbre: ActeUpdateTimbre;
  classification: ActeUpdateClassification;
  mots_cles: ActeUpdateMotsCles;
  statut: ActeUpdateStatut;
  acte_modifie_par: ActeUpdateActeModifiePar;
  signataires: ActeUpdateSignataires;
  version: ActeUpdateVersion;
  fichier_associe: ActeUpdateFichierAssocie;
  date_enregistrement: ActeUpdateDateEnregistrement;
  utilisateur_modification: ActeUpdateUtilisateurModification;
  actes_references: ActeUpdateActesReferences;
  actes_applications: ActeUpdateActesApplications;
  actes_modifies: ActeUpdateActesModifies;
  actes_modificateurs: ActeUpdateActesModificateurs;
  actes_enfants: ActeUpdateActesEnfants;
  acte_original: ActeUpdateActeOriginal;
}
