/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { ActeCreateTypeActe } from "./acteCreateTypeActe";
import type { ActeCreateTimbre } from "./acteCreateTimbre";
import type { ActeCreateDateCreation } from "./acteCreateDateCreation";
import type { ActeCreateClassification } from "./acteCreateClassification";
import type { ActeCreateObjet } from "./acteCreateObjet";
import type { ActeCreateStatut } from "./acteCreateStatut";
import type { ActeCreateDescription } from "./acteCreateDescription";
import type { ActeCreateMotsCles } from "./acteCreateMotsCles";
import type { ActeCreateDateEntreeVigueur } from "./acteCreateDateEntreeVigueur";
import type { ActeCreateDateExpiration } from "./acteCreateDateExpiration";
import type { ActeCreateDateEnregistrement } from "./acteCreateDateEnregistrement";
import type { ActeCreateAuteur } from "./acteCreateAuteur";
import type { ActeCreateSignataires } from "./acteCreateSignataires";
import type { ActeCreateFichierAssocie } from "./acteCreateFichierAssocie";
import type { ActeCreateBaseLegale } from "./acteCreateBaseLegale";
import type { ActeCreatePublicCible } from "./acteCreatePublicCible";
import type { ActeCreateDomaineApplication } from "./acteCreateDomaineApplication";
import type { ActeCreateLieuApplication } from "./acteCreateLieuApplication";
import type { ActeCreateActeModifiePar } from "./acteCreateActeModifiePar";
import type { ActeCreateVersion } from "./acteCreateVersion";
import type { ActeCreateUtilisateurModification } from "./acteCreateUtilisateurModification";
import type { ActeCreateActesReferences } from "./acteCreateActesReferences";
import type { ActeCreateActesApplications } from "./acteCreateActesApplications";
import type { ActeCreateActesModifies } from "./acteCreateActesModifies";
import type { ActeCreateActesModificateurs } from "./acteCreateActesModificateurs";
import type { ActeCreateActesEnfants } from "./acteCreateActesEnfants";
import type { ActeCreateActeOriginal } from "./acteCreateActeOriginal";

export interface ActeCreate {
  type_acte: ActeCreateTypeActe;
  numero: string;
  timbre: ActeCreateTimbre;
  date_creation: ActeCreateDateCreation;
  classification: ActeCreateClassification;
  objet: ActeCreateObjet;
  statut: ActeCreateStatut;
  description: ActeCreateDescription;
  mots_cles: ActeCreateMotsCles;
  date_entree_vigueur: ActeCreateDateEntreeVigueur;
  date_expiration: ActeCreateDateExpiration;
  date_enregistrement: ActeCreateDateEnregistrement;
  auteur: ActeCreateAuteur;
  signataires: ActeCreateSignataires;
  fichier_associe: ActeCreateFichierAssocie;
  base_legale: ActeCreateBaseLegale;
  public_cible: ActeCreatePublicCible;
  domaine_application: ActeCreateDomaineApplication;
  lieu_application: ActeCreateLieuApplication;
  acte_modifie_par: ActeCreateActeModifiePar;
  version: ActeCreateVersion;
  utilisateur_modification: ActeCreateUtilisateurModification;
  actes_references: ActeCreateActesReferences;
  actes_applications: ActeCreateActesApplications;
  actes_modifies: ActeCreateActesModifies;
  actes_modificateurs: ActeCreateActesModificateurs;
  actes_enfants: ActeCreateActesEnfants;
  acte_original: ActeCreateActeOriginal;
}
