// AUTO-GENERATED — DO NOT EDIT
  export const acteCreateFields = [
    { key: "numero", type: "string" },
  { key: "objet", type: "null | string" },
  { key: "type_acte", type: "null | string" },
  { key: "description", type: "null | string" },
  { key: "date_creation", type: "null | Date" },
  { key: "date_entree_vigueur", type: "null | Date" },
  { key: "date_expiration", type: "null | Date" },
  { key: "auteur", type: "null | string" },
  { key: "base_legale", type: "null | string" },
  { key: "public_cible", type: "null | string" },
  { key: "domaine_application", type: "null | string" },
  { key: "lieu_application", type: "null | string" },
  { key: "timbre", type: "null | string" },
  { key: "classification", type: "null | string" },
  { key: "mots_cles", type: "null | string" },
  { key: "statut", type: "null | string" },
  { key: "acte_modifie_par", type: "null | string" },
  { key: "signataires", type: "null | string" },
  { key: "version", type: "null | number" },
  { key: "fichier_associe", type: "null | string" },
  { key: "date_enregistrement", type: "null | Date" },
  { key: "utilisateur_modification", type: "null | string" },
  { key: "actes_references", type: "null | string" },
  { key: "actes_applications", type: "null | string" },
  { key: "actes_modifies", type: "null | string" },
  { key: "actes_modificateurs", type: "null | string" },
  { key: "actes_enfants", type: "null | string" },
  { key: "acte_original", type: "null | string" },
  ] as const;
  