/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */

export type GetColumnsAllApiTablesColumnsGetParams = {
  /**
   * Grid name, e.g., 'person', 'users', 'actes'
   */
  gn: string;
};
