/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */

export type GetDataApiTablesDataGetParams = {
  gn: string;
  page?: number;
  rows?: number;
  sidx?: string | null;
  sord?: string;
  search?: boolean | null;
  filters?: string | null;
  extra_data?: string | null;
};
