/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { UserSessionCreateIpAddress } from './userSessionCreateIpAddress';
import type { UserSessionCreateUserAgent } from './userSessionCreateUserAgent';
import type { UserSessionCreateCreatedAt } from './userSessionCreateCreatedAt';
import type { UserSessionCreateLastActive } from './userSessionCreateLastActive';

export interface UserSessionCreate {
  identifier: string;
  ip_address?: UserSessionCreateIpAddress;
  user_agent?: UserSessionCreateUserAgent;
  created_at?: UserSessionCreateCreatedAt;
  last_active?: UserSessionCreateLastActive;
}
