/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateUsername } from "./userUpdateUsername";
import type { UserUpdateEmail } from "./userUpdateEmail";
import type { UserUpdatePhone } from "./userUpdatePhone";

export interface UserUpdate {
  username?: UserUpdateUsername;
  email?: UserUpdateEmail;
  phone?: UserUpdatePhone;
}
