/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */

export interface UserSessionRead {
  id: string;
  user_id: number;
  ip_address: string;
  user_agent: string;
  created_at: Date;
  last_active: Date;
  is_active: boolean;
}
