/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { UserSessionUpdateLastActive } from "./userSessionUpdateLastActive";
import type { UserSessionUpdateIsActive } from "./userSessionUpdateIsActive";

export interface UserSessionUpdate {
  last_active?: UserSessionUpdateLastActive;
  is_active?: UserSessionUpdateIsActive;
}
