/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationErrorLocItem } from "./validationErrorLocItem";

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}
