/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetColumnsAllApiTablesColumnsGet200Item,
  GetColumnsAllApiTablesColumnsGetParams,
  GetDataApiTablesDataGetParams,
} from "../../schemas";

import { customAxios } from "../../axiosInstance";

export const getTables = () => {
  /**
   * @summary Get Columns All
   */
  const getColumnsAllApiTablesColumnsGet = (
    params: GetColumnsAllApiTablesColumnsGetParams,
  ) => {
    return customAxios<GetColumnsAllApiTablesColumnsGet200Item[]>({
      url: `/api/v1/tables/columns`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Get Data
   */
  const getDataApiTablesDataGet = (params: GetDataApiTablesDataGetParams) => {
    return customAxios<unknown>({
      url: `/api/v1/tables/data`,
      method: "GET",
      params,
    });
  };
  return { getColumnsAllApiTablesColumnsGet, getDataApiTablesDataGet };
};
export type GetColumnsAllApiTablesColumnsGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getTables>["getColumnsAllApiTablesColumnsGet"]>
  >
>;
export type GetDataApiTablesDataGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTables>["getDataApiTablesDataGet"]>>
>;
