/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { GetColumnsAllApiTablesColumnsGet200Item } from "../../schemas";

import { customAxios } from "../../axiosInstance";

export const getTables = () => {
  /**
   * @summary Get Columns All
   */
  const getColumnsAllApiTablesColumnsGet = () => {
    return customAxios<GetColumnsAllApiTablesColumnsGet200Item[]>({
      url: `/api/v1/tables/columns`,
      method: "GET",
    });
  };
  /**
   * @summary Get Data
   */
  const getDataApiTablesDataGet = () => {
    return customAxios<unknown>({ url: `/api/v1/tables/data`, method: "GET" });
  };
  return { getColumnsAllApiTablesColumnsGet, getDataApiTablesDataGet };
};
export type GetColumnsAllApiTablesColumnsGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getTables>["getColumnsAllApiTablesColumnsGet"]>
  >
>;
export type GetDataApiTablesDataGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTables>["getDataApiTablesDataGet"]>>
>;
