/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ActeCreate,
  ActeRead,
  ActeUpdate,
  AuthResponse,
  CheckEmailApiUsersCheckEmailGetParams,
  CheckPhoneApiUsersCheckPhoneGetParams,
  CheckUsernameApiUsersCheckUsernameGetParams,
  LoginRequest,
  RegisterRequest,
  UserCreate,
  UserRead,
  UserSessionCreate,
  UserSessionRead,
  UserSessionUpdate,
  UserUpdate
} from './schemas';

export const getAeroRh = () => {
/**
 * @summary Login
 */
const loginApiAuthLoginPost = <TData = AxiosResponse<AuthResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }

/**
 * @summary Register
 */
const registerApiAuthRegisterPost = <TData = AxiosResponse<AuthResponse>>(
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/register`,
      registerRequest,options
    );
  }

/**
 * @summary Check Username
 */
const checkUsernameApiUsersCheckUsernameGet = <TData = AxiosResponse<unknown>>(
    params: CheckUsernameApiUsersCheckUsernameGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/check/username`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Check Email
 */
const checkEmailApiUsersCheckEmailGet = <TData = AxiosResponse<unknown>>(
    params: CheckEmailApiUsersCheckEmailGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/check/email`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Check Phone
 */
const checkPhoneApiUsersCheckPhoneGet = <TData = AxiosResponse<unknown>>(
    params: CheckPhoneApiUsersCheckPhoneGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/check/phone`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary List Users
 */
const listUsersApiUsersGet = <TData = AxiosResponse<UserRead[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/`,options
    );
  }

/**
 * @summary Create User Route
 */
const createUserRouteApiUsersPost = <TData = AxiosResponse<UserRead>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/users/`,
      userCreate,options
    );
  }

/**
 * @summary Read User
 */
const readUserApiUsersUserIdGet = <TData = AxiosResponse<UserRead>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/${userId}`,options
    );
  }

/**
 * @summary Update User Route
 */
const updateUserRouteApiUsersUserIdPatch = <TData = AxiosResponse<UserRead>>(
    userId: number,
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/users/${userId}`,
      userUpdate,options
    );
  }

/**
 * @summary Delete User Route
 */
const deleteUserRouteApiUsersUserIdDelete = <TData = AxiosResponse<unknown>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/users/${userId}`,options
    );
  }

/**
 * @summary Create Session
 */
const createSessionApiSessionsPost = <TData = AxiosResponse<UserSessionRead>>(
    userSessionCreate: UserSessionCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/sessions`,
      userSessionCreate,options
    );
  }

/**
 * @summary Create Session 
 */
const createSessionApiSessionsPost = <TData = AxiosResponse<UserSessionRead>>(
    userSessionCreate: UserSessionCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/sessions/`,
      userSessionCreate,options
    );
  }

/**
 * @summary Get Current Session
 */
const getCurrentSessionApiSessionsCurrentGet = <TData = AxiosResponse<UserSessionRead>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/sessions/current`,options
    );
  }

/**
 * @summary Get Active Sessions
 */
const getActiveSessionsApiSessionsActiveUserIdGet = <TData = AxiosResponse<UserSessionRead[]>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/sessions/active/${userId}`,options
    );
  }

/**
 * @summary Get Session By Id
 */
const getSessionByIdApiSessionsSessionIdGet = <TData = AxiosResponse<UserSessionRead>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/sessions/${sessionId}`,options
    );
  }

/**
 * @summary Update Session
 */
const updateSessionApiSessionsSessionIdPatch = <TData = AxiosResponse<UserSessionRead>>(
    sessionId: string,
    userSessionUpdate: UserSessionUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/sessions/${sessionId}`,
      userSessionUpdate,options
    );
  }

/**
 * @summary Deactivate Session
 */
const deactivateSessionApiSessionsSessionIdDelete = <TData = AxiosResponse<UserSessionRead>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/sessions/${sessionId}`,options
    );
  }

/**
 * @summary Read Actes
 */
const readActesApiActesGet = <TData = AxiosResponse<ActeRead[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/actes/`,options
    );
  }

/**
 * @summary Create Acte
 */
const createActeApiActesPost = <TData = AxiosResponse<ActeRead>>(
    acteCreate: ActeCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/actes/`,
      acteCreate,options
    );
  }

/**
 * @summary Read Acte
 */
const readActeApiActesActeIdGet = <TData = AxiosResponse<ActeRead>>(
    acteId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/actes/${acteId}`,options
    );
  }

/**
 * @summary Update Acte
 */
const updateActeApiActesActeIdPatch = <TData = AxiosResponse<ActeRead>>(
    acteId: number,
    acteUpdate: ActeUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/actes/${acteId}`,
      acteUpdate,options
    );
  }

/**
 * @summary Delete Acte
 */
const deleteActeApiActesActeIdDelete = <TData = AxiosResponse<unknown>>(
    acteId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/actes/${acteId}`,options
    );
  }

/**
 * @summary Read Root
 */
const readRootGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,options
    );
  }

return {loginApiAuthLoginPost,registerApiAuthRegisterPost,checkUsernameApiUsersCheckUsernameGet,checkEmailApiUsersCheckEmailGet,checkPhoneApiUsersCheckPhoneGet,listUsersApiUsersGet,createUserRouteApiUsersPost,readUserApiUsersUserIdGet,updateUserRouteApiUsersUserIdPatch,deleteUserRouteApiUsersUserIdDelete,createSessionApiSessionsPost,createSessionApiSessionsPost,getCurrentSessionApiSessionsCurrentGet,getActiveSessionsApiSessionsActiveUserIdGet,getSessionByIdApiSessionsSessionIdGet,updateSessionApiSessionsSessionIdPatch,deactivateSessionApiSessionsSessionIdDelete,readActesApiActesGet,createActeApiActesPost,readActeApiActesActeIdGet,updateActeApiActesActeIdPatch,deleteActeApiActesActeIdDelete,readRootGet}};
export type LoginApiAuthLoginPostResult = AxiosResponse<AuthResponse>
export type RegisterApiAuthRegisterPostResult = AxiosResponse<AuthResponse>
export type CheckUsernameApiUsersCheckUsernameGetResult = AxiosResponse<unknown>
export type CheckEmailApiUsersCheckEmailGetResult = AxiosResponse<unknown>
export type CheckPhoneApiUsersCheckPhoneGetResult = AxiosResponse<unknown>
export type ListUsersApiUsersGetResult = AxiosResponse<UserRead[]>
export type CreateUserRouteApiUsersPostResult = AxiosResponse<UserRead>
export type ReadUserApiUsersUserIdGetResult = AxiosResponse<UserRead>
export type UpdateUserRouteApiUsersUserIdPatchResult = AxiosResponse<UserRead>
export type DeleteUserRouteApiUsersUserIdDeleteResult = AxiosResponse<unknown>
export type CreateSessionApiSessionsPostResult = AxiosResponse<UserSessionRead>
export type CreateSessionApiSessionsPostResult = AxiosResponse<UserSessionRead>
export type GetCurrentSessionApiSessionsCurrentGetResult = AxiosResponse<UserSessionRead>
export type GetActiveSessionsApiSessionsActiveUserIdGetResult = AxiosResponse<UserSessionRead[]>
export type GetSessionByIdApiSessionsSessionIdGetResult = AxiosResponse<UserSessionRead>
export type UpdateSessionApiSessionsSessionIdPatchResult = AxiosResponse<UserSessionRead>
export type DeactivateSessionApiSessionsSessionIdDeleteResult = AxiosResponse<UserSessionRead>
export type ReadActesApiActesGetResult = AxiosResponse<ActeRead[]>
export type CreateActeApiActesPostResult = AxiosResponse<ActeRead>
export type ReadActeApiActesActeIdGetResult = AxiosResponse<ActeRead>
export type UpdateActeApiActesActeIdPatchResult = AxiosResponse<ActeRead>
export type DeleteActeApiActesActeIdDeleteResult = AxiosResponse<unknown>
export type ReadRootGetResult = AxiosResponse<unknown>
