/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ActeCreate,
  ActeRead,
  ActeUpdate
} from '../schemas';





  export const getActes = () => {
/**
 * @summary Read Actes
 */
const readActesApiActesGet = <TData = AxiosResponse<ActeRead[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/actes/`,options
    );
  }
/**
 * @summary Create Acte
 */
const createActeApiActesPost = <TData = AxiosResponse<ActeRead>>(
    acteCreate: ActeCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/actes/`,
      acteCreate,options
    );
  }
/**
 * @summary Read Acte
 */
const readActeApiActesActeIdGet = <TData = AxiosResponse<ActeRead>>(
    acteId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/actes/${acteId}`,options
    );
  }
/**
 * @summary Update Acte
 */
const updateActeApiActesActeIdPatch = <TData = AxiosResponse<ActeRead>>(
    acteId: number,
    acteUpdate: ActeUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/actes/${acteId}`,
      acteUpdate,options
    );
  }
/**
 * @summary Delete Acte
 */
const deleteActeApiActesActeIdDelete = <TData = AxiosResponse<unknown>>(
    acteId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/actes/${acteId}`,options
    );
  }
return {readActesApiActesGet,createActeApiActesPost,readActeApiActesActeIdGet,updateActeApiActesActeIdPatch,deleteActeApiActesActeIdDelete}};
export type ReadActesApiActesGetResult = AxiosResponse<ActeRead[]>
export type CreateActeApiActesPostResult = AxiosResponse<ActeRead>
export type ReadActeApiActesActeIdGetResult = AxiosResponse<ActeRead>
export type UpdateActeApiActesActeIdPatchResult = AxiosResponse<ActeRead>
export type DeleteActeApiActesActeIdDeleteResult = AxiosResponse<unknown>
