/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthResponse,
  LoginRequest,
  RegisterRequest
} from '../schemas';





  export const getAuth = () => {
/**
 * @summary Login
 */
const loginApiAuthLoginPost = <TData = AxiosResponse<AuthResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }
/**
 * @summary Register
 */
const registerApiAuthRegisterPost = <TData = AxiosResponse<AuthResponse>>(
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/auth/register`,
      registerRequest,options
    );
  }
return {loginApiAuthLoginPost,registerApiAuthRegisterPost}};
export type LoginApiAuthLoginPostResult = AxiosResponse<AuthResponse>
export type RegisterApiAuthRegisterPostResult = AxiosResponse<AuthResponse>
