/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  UserSessionCreate,
  UserSessionRead,
  UserSessionUpdate
} from '../schemas';





  export const getSessions = () => {
/**
 * @summary Create Session
 */
const createSessionApiSessionsPost = <TData = AxiosResponse<UserSessionRead>>(
    userSessionCreate: UserSessionCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/sessions`,
      userSessionCreate,options
    );
  }
/**
 * @summary Create Session 
 */
const createSessionApiSessionsPost = <TData = AxiosResponse<UserSessionRead>>(
    userSessionCreate: UserSessionCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/sessions/`,
      userSessionCreate,options
    );
  }
/**
 * @summary Get Current Session
 */
const getCurrentSessionApiSessionsCurrentGet = <TData = AxiosResponse<UserSessionRead>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/sessions/current`,options
    );
  }
/**
 * @summary Get Active Sessions
 */
const getActiveSessionsApiSessionsActiveUserIdGet = <TData = AxiosResponse<UserSessionRead[]>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/sessions/active/${userId}`,options
    );
  }
/**
 * @summary Get Session By Id
 */
const getSessionByIdApiSessionsSessionIdGet = <TData = AxiosResponse<UserSessionRead>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/sessions/${sessionId}`,options
    );
  }
/**
 * @summary Update Session
 */
const updateSessionApiSessionsSessionIdPatch = <TData = AxiosResponse<UserSessionRead>>(
    sessionId: string,
    userSessionUpdate: UserSessionUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/sessions/${sessionId}`,
      userSessionUpdate,options
    );
  }
/**
 * @summary Deactivate Session
 */
const deactivateSessionApiSessionsSessionIdDelete = <TData = AxiosResponse<UserSessionRead>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/sessions/${sessionId}`,options
    );
  }
return {createSessionApiSessionsPost,createSessionApiSessionsPost,getCurrentSessionApiSessionsCurrentGet,getActiveSessionsApiSessionsActiveUserIdGet,getSessionByIdApiSessionsSessionIdGet,updateSessionApiSessionsSessionIdPatch,deactivateSessionApiSessionsSessionIdDelete}};
export type CreateSessionApiSessionsPostResult = AxiosResponse<UserSessionRead>
export type CreateSessionApiSessionsPostResult = AxiosResponse<UserSessionRead>
export type GetCurrentSessionApiSessionsCurrentGetResult = AxiosResponse<UserSessionRead>
export type GetActiveSessionsApiSessionsActiveUserIdGetResult = AxiosResponse<UserSessionRead[]>
export type GetSessionByIdApiSessionsSessionIdGetResult = AxiosResponse<UserSessionRead>
export type UpdateSessionApiSessionsSessionIdPatchResult = AxiosResponse<UserSessionRead>
export type DeactivateSessionApiSessionsSessionIdDeleteResult = AxiosResponse<UserSessionRead>
