/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CheckEmailApiUsersCheckEmailGetParams,
  CheckPhoneApiUsersCheckPhoneGetParams,
  CheckUsernameApiUsersCheckUsernameGetParams,
  UserCreate,
  UserRead,
  UserUpdate
} from '../schemas';





  export const getUsers = () => {
/**
 * @summary Check Username
 */
const checkUsernameApiUsersCheckUsernameGet = <TData = AxiosResponse<unknown>>(
    params: CheckUsernameApiUsersCheckUsernameGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/check/username`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Check Email
 */
const checkEmailApiUsersCheckEmailGet = <TData = AxiosResponse<unknown>>(
    params: CheckEmailApiUsersCheckEmailGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/check/email`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary Check Phone
 */
const checkPhoneApiUsersCheckPhoneGet = <TData = AxiosResponse<unknown>>(
    params: CheckPhoneApiUsersCheckPhoneGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/check/phone`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * @summary List Users
 */
const listUsersApiUsersGet = <TData = AxiosResponse<UserRead[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/`,options
    );
  }
/**
 * @summary Create User Route
 */
const createUserRouteApiUsersPost = <TData = AxiosResponse<UserRead>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/users/`,
      userCreate,options
    );
  }
/**
 * @summary Read User
 */
const readUserApiUsersUserIdGet = <TData = AxiosResponse<UserRead>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/users/${userId}`,options
    );
  }
/**
 * @summary Update User Route
 */
const updateUserRouteApiUsersUserIdPatch = <TData = AxiosResponse<UserRead>>(
    userId: number,
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/users/${userId}`,
      userUpdate,options
    );
  }
/**
 * @summary Delete User Route
 */
const deleteUserRouteApiUsersUserIdDelete = <TData = AxiosResponse<unknown>>(
    userId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/users/${userId}`,options
    );
  }
return {checkUsernameApiUsersCheckUsernameGet,checkEmailApiUsersCheckEmailGet,checkPhoneApiUsersCheckPhoneGet,listUsersApiUsersGet,createUserRouteApiUsersPost,readUserApiUsersUserIdGet,updateUserRouteApiUsersUserIdPatch,deleteUserRouteApiUsersUserIdDelete}};
export type CheckUsernameApiUsersCheckUsernameGetResult = AxiosResponse<unknown>
export type CheckEmailApiUsersCheckEmailGetResult = AxiosResponse<unknown>
export type CheckPhoneApiUsersCheckPhoneGetResult = AxiosResponse<unknown>
export type ListUsersApiUsersGetResult = AxiosResponse<UserRead[]>
export type CreateUserRouteApiUsersPostResult = AxiosResponse<UserRead>
export type ReadUserApiUsersUserIdGetResult = AxiosResponse<UserRead>
export type UpdateUserRouteApiUsersUserIdPatchResult = AxiosResponse<UserRead>
export type DeleteUserRouteApiUsersUserIdDeleteResult = AxiosResponse<unknown>
