/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type {
  UserSessionCreate,
  UserSessionRead,
  UserSessionUpdate,
} from "../../schemas";

import { customAxios } from "../../axiosInstance";

export const getSessions = () => {
  /**
   * @summary Create Session
   */
  const createSessionApiSessionsPost = (
    userSessionCreate: UserSessionCreate,
  ) => {
    return customAxios<UserSessionRead>({
      url: `/api/v1/sessions`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: userSessionCreate,
    });
  };
  /**
   * @summary Get Current Session
   */
  const getCurrentSessionApiSessionsCurrentGet = () => {
    return customAxios<UserSessionRead>({
      url: `/api/v1/sessions/current`,
      method: "GET",
    });
  };
  /**
   * @summary Get Active Sessions
   */
  const getActiveSessionsApiSessionsActiveUserIdGet = (userId: number) => {
    return customAxios<UserSessionRead[]>({
      url: `/api/v1/sessions/active/${userId}`,
      method: "GET",
    });
  };
  /**
   * @summary Get Session By Id
   */
  const getSessionByIdApiSessionsSessionIdGet = (sessionId: string) => {
    return customAxios<UserSessionRead>({
      url: `/api/v1/sessions/${sessionId}`,
      method: "GET",
    });
  };
  /**
   * @summary Update Session
   */
  const updateSessionApiSessionsSessionIdPatch = (
    sessionId: string,
    userSessionUpdate: UserSessionUpdate,
  ) => {
    return customAxios<UserSessionRead>({
      url: `/api/v1/sessions/${sessionId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: userSessionUpdate,
    });
  };
  /**
   * @summary Deactivate Session
   */
  const deactivateSessionApiSessionsSessionIdDelete = (sessionId: string) => {
    return customAxios<UserSessionRead>({
      url: `/api/v1/sessions/${sessionId}`,
      method: "DELETE",
    });
  };
  return {
    createSessionApiSessionsPost,
    getCurrentSessionApiSessionsCurrentGet,
    getActiveSessionsApiSessionsActiveUserIdGet,
    getSessionByIdApiSessionsSessionIdGet,
    updateSessionApiSessionsSessionIdPatch,
    deactivateSessionApiSessionsSessionIdDelete,
  };
};
export type CreateSessionApiSessionsPostResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSessions>["createSessionApiSessionsPost"]>
  >
>;
export type GetCurrentSessionApiSessionsCurrentGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSessions>["getCurrentSessionApiSessionsCurrentGet"]
    >
  >
>;
export type GetActiveSessionsApiSessionsActiveUserIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSessions
      >["getActiveSessionsApiSessionsActiveUserIdGet"]
    >
  >
>;
export type GetSessionByIdApiSessionsSessionIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSessions>["getSessionByIdApiSessionsSessionIdGet"]
    >
  >
>;
export type UpdateSessionApiSessionsSessionIdPatchResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSessions>["updateSessionApiSessionsSessionIdPatch"]
    >
  >
>;
export type DeactivateSessionApiSessionsSessionIdDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSessions
      >["deactivateSessionApiSessionsSessionIdDelete"]
    >
  >
>;
