/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type { ActeCreate, ActeRead, ActeUpdate } from "../../schemas";

import { customAxios } from "../../axiosInstance";

export const getActes = () => {
  /**
   * @summary Read Actes
   */
  const readActesApiActesGet = () => {
    return customAxios<ActeRead[]>({ url: `/api/v2/api/actes`, method: "GET" });
  };
  /**
   * @summary Create Acte
   */
  const createActeApiActesPost = (acteCreate: ActeCreate) => {
    return customAxios<ActeRead>({
      url: `/api/v2/api/actes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: acteCreate,
    });
  };
  /**
   * @summary Read Acte
   */
  const readActeApiActesActeIdGet = (acteId: number) => {
    return customAxios<ActeRead>({
      url: `/api/v2/api/actes/${acteId}`,
      method: "GET",
    });
  };
  /**
   * @summary Update Acte
   */
  const updateActeApiActesActeIdPatch = (
    acteId: number,
    acteUpdate: ActeUpdate,
  ) => {
    return customAxios<ActeRead>({
      url: `/api/v2/api/actes/${acteId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: acteUpdate,
    });
  };
  /**
   * @summary Delete Acte
   */
  const deleteActeApiActesActeIdDelete = (acteId: number) => {
    return customAxios<unknown>({
      url: `/api/v2/api/actes/${acteId}`,
      method: "DELETE",
    });
  };
  return {
    readActesApiActesGet,
    createActeApiActesPost,
    readActeApiActesActeIdGet,
    updateActeApiActesActeIdPatch,
    deleteActeApiActesActeIdDelete,
  };
};
export type ReadActesApiActesGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getActes>["readActesApiActesGet"]>>
>;
export type CreateActeApiActesPostResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getActes>["createActeApiActesPost"]>>
>;
export type ReadActeApiActesActeIdGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getActes>["readActeApiActesActeIdGet"]>>
>;
export type UpdateActeApiActesActeIdPatchResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getActes>["updateActeApiActesActeIdPatch"]>
  >
>;
export type DeleteActeApiActesActeIdDeleteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getActes>["deleteActeApiActesActeIdDelete"]>
  >
>;
