/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import { customAxios } from "../../axiosInstance";

export const getDefault = () => {
  /**
   * @summary Read Root
   */
  const readRootGet = () => {
    return customAxios<unknown>({ url: `/`, method: "GET" });
  };
  return {};
};
