/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * AERO RH
 * OpenAPI spec version: 0.1.0
 */
import type {
  CheckEmailApiUsersCheckEmailGetParams,
  CheckPhoneApiUsersCheckPhoneGetParams,
  CheckUsernameApiUsersCheckUsernameGetParams,
  UserCreate,
  UserRead,
  UserUpdate,
} from "../../schemas";

import { customAxios } from "../../axiosInstance";

export const getUsers = () => {
  /**
   * @summary Check Username
   */
  const checkUsernameApiUsersCheckUsernameGet = (
    params: CheckUsernameApiUsersCheckUsernameGetParams,
  ) => {
    return customAxios<unknown>({
      url: `/api/users/check/username`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Check Email
   */
  const checkEmailApiUsersCheckEmailGet = (
    params: CheckEmailApiUsersCheckEmailGetParams,
  ) => {
    return customAxios<unknown>({
      url: `/api/users/check/email`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary Check Phone
   */
  const checkPhoneApiUsersCheckPhoneGet = (
    params: CheckPhoneApiUsersCheckPhoneGetParams,
  ) => {
    return customAxios<unknown>({
      url: `/api/users/check/phone`,
      method: "GET",
      params,
    });
  };
  /**
   * @summary List Users
   */
  const listUsersApiUsersGet = () => {
    return customAxios<UserRead[]>({ url: `/api/users/`, method: "GET" });
  };
  /**
   * @summary Create User Route
   */
  const createUserRouteApiUsersPost = (userCreate: UserCreate) => {
    return customAxios<UserRead>({
      url: `/api/users/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: userCreate,
    });
  };
  /**
   * @summary Read User
   */
  const readUserApiUsersUserIdGet = (userId: number) => {
    return customAxios<UserRead>({
      url: `/api/users/${userId}`,
      method: "GET",
    });
  };
  /**
   * @summary Update User Route
   */
  const updateUserRouteApiUsersUserIdPatch = (
    userId: number,
    userUpdate: UserUpdate,
  ) => {
    return customAxios<UserRead>({
      url: `/api/users/${userId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: userUpdate,
    });
  };
  /**
   * @summary Delete User Route
   */
  const deleteUserRouteApiUsersUserIdDelete = (userId: number) => {
    return customAxios<unknown>({
      url: `/api/users/${userId}`,
      method: "DELETE",
    });
  };
  return {
    checkUsernameApiUsersCheckUsernameGet,
    checkEmailApiUsersCheckEmailGet,
    checkPhoneApiUsersCheckPhoneGet,
    listUsersApiUsersGet,
    createUserRouteApiUsersPost,
    readUserApiUsersUserIdGet,
    updateUserRouteApiUsersUserIdPatch,
    deleteUserRouteApiUsersUserIdDelete,
  };
};
export type CheckUsernameApiUsersCheckUsernameGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsers>["checkUsernameApiUsersCheckUsernameGet"]
    >
  >
>;
export type CheckEmailApiUsersCheckEmailGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getUsers>["checkEmailApiUsersCheckEmailGet"]>
  >
>;
export type CheckPhoneApiUsersCheckPhoneGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getUsers>["checkPhoneApiUsersCheckPhoneGet"]>
  >
>;
export type ListUsersApiUsersGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>["listUsersApiUsersGet"]>>
>;
export type CreateUserRouteApiUsersPostResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getUsers>["createUserRouteApiUsersPost"]>
  >
>;
export type ReadUserApiUsersUserIdGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUsers>["readUserApiUsersUserIdGet"]>>
>;
export type UpdateUserRouteApiUsersUserIdPatchResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsers>["updateUserRouteApiUsersUserIdPatch"]
    >
  >
>;
export type DeleteUserRouteApiUsersUserIdDeleteResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getUsers>["deleteUserRouteApiUsersUserIdDelete"]
    >
  >
>;
